GET http://localhost:8080/employee
###
GET http://localhost:8080/employee/add?firstName=Иван&lastName=Иванов
###
GET http://localhost:8080/employee/add?firstName=Коля&lastName=Петров&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Женя&lastName=Котляров&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Женя1&lastName=Котляров&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Женя&lastName=Котляров2&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=женя&lastName=Котляров&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Женя&lastName=котляров&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Женя&lastName=Кот ляров&salary=100000&departmentId=1
###
GET http://localhost:8080/employee/findAll
###
GET http://localhost:8080/employee/find?firstName=Женя&lastName=Котляров
###
GET http://localhost:8080/employee/remove?firstName=Женя&lastName=Котляров
###
GET http://localhost:8080/employee/findAll
###
GET http://localhost:8080/employee/remove?firstName=Иван&lastName=Иванов
###
GET http://localhost:8080/employee/remove?firstName=Коля&lastName=Петров
###
GET http://localhost:8080/employee/remove?firstName=Женя&lastName=Котляров2
###
GET http://localhost:8080/employee/findAll
###
GET http://localhost:8080/departments/all
###
GET http://localhost:8080/departments/max-salary?departmentId=1
###
GET http://localhost:8080/departments/max-salary?departmentId=0
###
GET http://localhost:8080/departments/min-salary?departmentId=0
###
GET http://localhost:8080/departments/min-salary?departmentId=3
###
GET http://localhost:8080/departments/min-salary?departmentId=2
###
GET http://localhost:8080/departments/all?departmentId=0
